name: Build Android APK Fast

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Install System Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git zip unzip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libgdbm-dev libnss3-dev libssl-dev libreadline-dev libffi-dev libsqlite3-dev tk-dev libgdbm-compat-dev libreoffice-dev libmpdec-dev
        pip3 install --user --upgrade buildozer Cython virtualenv

    - name: Build APK
      run: |
        export PATH=$PATH:~/.local/bin
        # Android lisanslarını otomatik olarak onaylama komutu:
        mkdir -p ~/.buildozer/android/platform/android-sdk/licenses
        echo -e "247a1c17b344f141474d1a437d2163a0e301575f\n84831b9409646a547e30b925b4d97d410d540307\nf9f0a54102b3a14a75e40600c3b9aa36afd2913b\n8933bad161af4178b1185d1a37fbf41ea5269c55\n2f132d725b44438e3bab2db1947d14e362497523\n6d1a6a5d18d8d72793d334e109d2ddc237e6d562" > ~/.buildozer/android/platform/android-sdk/licenses/android-sdk-license
        yes | buildozer android debug
